name: Lint

on: [push, pull_request]

jobs:
  lint:
    uses: ./.github/workflows/python-setup.yml
    with:
      requirements-file: requirements.txt

  run-linters:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run linters
        run: |
          mypy .
          pylint .
          pycodestyle .
