name: Playwright Tests (Python)

on: [push, pull_request]

jobs:
  test-functional:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        test_path: [tests/]
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: |
          python -m playwright install --with-deps

      - name: Run Tests
        run: |
          pytest ${{ matrix.test_path }} --browser ${{ matrix.browser }} --tracing=retain-on-failure
        continue-on-error: true

      - name: Upload Playwright Traces
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/

  test-visual:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        test_path: [tests_visual/]
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
  
      - name: Install Playwright Browsers
        run: |
            python -m playwright install --with-deps
  
      - name: Run Tests
        run: |
          pytest ${{ matrix.test_path }} --browser ${{ matrix.browser }} --tracing=retain-on-failure
        continue-on-error: true

      - name: Upload Snapshots
        uses: actions/upload-artifact@v4
        with:
          name: snapshots-${{ matrix.browser }}
          path: |
            ${{ matrix.test_path }}/__snapshots__/

      - name: Upload Playwright Traces
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
