name: Playwright Tests (Python)

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright and browsers
        run: python -m playwright install --with-deps

  test-functional:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        test_path: [tests/]
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: |
          pytest ${{ matrix.test_path }} --browser ${{ matrix.browser }} --tracing=retain-on-failure

      - name: Upload Playwright traces
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/

  test-visual:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        test_path: [tests_visual/]
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        run: |
          pytest ${{ matrix.test_path }} --browser ${{ matrix.browser }} --tracing=retain-on-failure

      - name: Upload Playwright traces
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-traces
          path: test-results/
