name: Python Setup

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.12.4'
      requirements-file:
        required: false
        type: string
        default: 'requirements.txt'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ inputs.python-version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements-file }}
